### ISSUE TITLE
Trouble with Singleton implementation

### ISSUE THREAD

**Issue by FSund** [manaporkun/UnityRuntimeTransformHandles#1]
Firstly, thanks a lot for this package, is has been very instructive!

I was having some trouble with using the handles in my own project, I was unable to move the handles, and they were not being highlighted when I moused over them. I noticed that the `HandleManager` under `DontDestroyOnLoad` during runtime did not have the same properties as I set in the Editor.

To me the logic here seems the wrong way around
https://github.com/manaporkun/UnityRuntimeTransformHandles/blob/ffb8127b63e0e749b1b2aa864376ae97b2b2454b/Packages/runtime-transform-handles/Runtime/Scripts/Utils/Singleton.cs#L27-L38

so I changed it to

```
protected virtual void Awake()
{
    if (_instance != null && _instance != this)
    {
        Destroy(gameObject);
        return;
    }

    _instance = this as T;
    DontDestroyOnLoad(gameObject);
}
```

which fixed my issue. I might just have a weird setup though, but wanted to hear your thoughts on the matter.

**Comment by manaporkun** [comment]
Hey there!

I'm so happy to hear that you found the package helpful and interesting. Your feedback has been incredibly valuable to me, and I'm grateful for your interest in the project.

I took a look at the code and made some tweaks based on your suggestions. Plus, I found some other potential bugs, so I fixed those too! You can check out all the changes on the singleton script I made in the following commit:

https://github.com/manaporkun/UnityRuntimeTransformHandles/commit/d6e2f627fd0a630aeb4196518933025690643032#diff-040adbbcb4634a86fa140a6aece4fa965eb6f01f5583e25dd572fa56c706d245

I think that these adjustments will address the issues you faced. But if you have any more questions or ideas, please don't hesitate to reach out.

Thanks again for your feedback! I'm happy to know that you're finding the package useful.

**Comment by FSund** [comment]
Hi,

I tried your latest code, and I'm getting the following error when the last object is deselected

```
KeyNotFoundException: The given key 'NativeTransformHandle(Clone) (TransformHandles.Handle)' was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <a01111b1273a40cc8673b44832e8a221>:0)
TransformHandles.TransformHandleManager.RemoveHandle (TransformHandles.Handle handle) (at Packages/runtime-transform-handles/Runtime/Scripts/TransformHandleManager.cs:149)
TransformHandles.Handle.OnDestroy () (at Packages/runtime-transform-handles/Runtime/Scripts/Handle.cs:50)
UnityEngine.Object:DestroyImmediate(Object)
TransformHandles.TransformHandleManager:DestroyHandle(Handle) (at Packages/runtime-transform-handles/Runtime/Scripts/TransformHandleManager.cs:171)
TransformHandles.TransformHandleManager:RemoveTarget(Transform, Handle) (at Packages/runtime-transform-handles/Runtime/Scripts/TransformHandleManager.cs:209)
ObjSelector:RemoveTarget(Transform) (at Assets/Scripts/ObjSelector.cs:144)
ObjSelector:Update() (at Assets/Scripts/ObjSelector.cs:86)
```

To reproduce: select any object via left click, then deselect it via right click.

Not a huge issue, everything seems to still work, but thought I should mention it.
